apiVersion: apps/v1
kind: Deployment
metadata:
  name: appweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appweb
  template:
    metadata:
      labels:
        app: appweb
    spec:
      containers:
        - name: appweb
          image: asergio68/fc3-desafio-2_react-frontend:latest
          ports:
            - containerPort: 3001
